import { chromium } from 'playwright'

const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
await page.goto('https://ra.333labs.tech/', { waitUntil: 'networkidle', timeout: 45000 })
await page.waitForTimeout(1500)

const section = page.locator('#intro-cards')
console.log('section count:', await section.count())
if (await section.count()) {
  console.log('cards:', await section.locator('> div > div > div').count())
  const text = (await section.innerText()).split('\n').filter(Boolean)
  console.log('text:', JSON.stringify(text))
  const heading = section.locator('h2').first()
  const hb = await heading.boundingBox()
  console.log('first h2 box:', hb && { w: Math.round(hb.width), h: Math.round(hb.height) })
  const red = await section.locator('h2 span').first().evaluate((el) => getComputedStyle(el).color)
  console.log('red accent:', red)
  const badge = section.locator('span[aria-hidden]').first()
  console.log('badge bg:', await badge.evaluate((el) => getComputedStyle(el).backgroundColor))
  const icons = await section.locator('svg').count()
  console.log('svg icons in section:', icons)
}
await page.screenshot({ path: '/root/ragilaluminium/storage/app/audit-evidence/2026-08-08/intro-cards/desktop.png', fullPage: false })
await browser.close()

const mob = await browser.newPage({ viewport: { width: 390, height: 844 } })
await mob.goto('https://ra.333labs.tech/', { waitUntil: 'networkidle', timeout: 45000 })
await mob.waitForTimeout(1200)
const ms = mob.locator('#intro-cards')
const before = await mob.locator('#promo').count()
const mb = await ms.boundingBox()
console.log('mobile section box:', mb && { x: Math.round(mb.x), y: Math.round(mb.y), w: Math.round(mb.width), h: Math.round(mb.height) })
console.log('promo exists:', before)
await mob.screenshot({ path: '/root/ragilaluminium/storage/app/audit-evidence/2026-08-08/intro-cards/mobile.png', fullPage: false })
await browser.close()
