/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "home": [],
    "about": [],
    "faq": [],
    "contact": [],
    "cara-pemesanan": [],
    "privacy": [],
    "terms": [],
    "catalog.index": [],
    "catalog.windows": [],
    "catalog.doors": [],
    "catalog.bouven": [],
    "search": [],
    "product.show": [
        {
            "name": "parent_sku",
            "required": true
        }
    ],
    "cart.index": [],
    "cart.count": [],
    "cart.add": [],
    "cart.update": [],
    "cart.remove": [],
    "reviews": [],
    "checkout.index": [],
    "checkout.validate": [],
    "checkout.place-order": [],
    "order.confirmation": [
        {
            "name": "order_number",
            "required": true
        }
    ],
    "order.count": [],
    "order.status": [],
    "order.status.lookup": [],
    "login": [],
    "login.post": [],
    "logout": [],
    "admin.dashboard": [],
    "admin.pages.branding": [],
    "admin.products.index": [],
    "admin.products.create": [],
    "admin.products.store": [],
    "admin.products.show": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.edit": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.update": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.archive": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.unarchive": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.variants.index": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.variants.store": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.variants.edit": [
        {
            "name": "variant",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.variants.update": [
        {
            "name": "variant",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.variants.archive": [
        {
            "name": "variant",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.attributes.index": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.attributes.store": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.attributes.update": [
        {
            "name": "attribute",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.media.index": [],
    "admin.products.media.byProduct": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.media.store": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.media.update": [
        {
            "name": "media",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.media.set-main": [
        {
            "name": "media",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.media.archive": [
        {
            "name": "media",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.media.redownload": [
        {
            "name": "media",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.imports.index": [],
    "admin.imports.create": [],
    "admin.imports.store": [],
    "admin.imports.show": [
        {
            "name": "import_job",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.imports.retry": [
        {
            "name": "import_job",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.imports.failed-rows": [
        {
            "name": "import_job",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.imports.correction-file": [
        {
            "name": "import_job",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.orders.index": [],
    "admin.orders.show": [
        {
            "name": "order",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.orders.status": [
        {
            "name": "order",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.payments.index": [],
    "admin.orders.payments": [
        {
            "name": "order",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.payments.store": [
        {
            "name": "order",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.payments.update": [
        {
            "name": "payment",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.shipping.index": [],
    "admin.shipping.show": [
        {
            "name": "shipping",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.shipping.refresh": [
        {
            "name": "shipping_record",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.whatsapp.templates.index": [],
    "admin.whatsapp.templates.store": [],
    "admin.whatsapp.templates.update": [
        {
            "name": "template",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.whatsapp.templates.activate": [
        {
            "name": "template",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.whatsapp.templates.deactivate": [
        {
            "name": "template",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.whatsapp.messages.index": [],
    "admin.orders.whatsapp": [
        {
            "name": "order",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.whatsapp.messages.show": [
        {
            "name": "message",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.analytics.store-performance": [],
    "admin.analytics.import-performance": [],
    "admin.pages.index": [],
    "admin.pages.create": [],
    "admin.pages.store": [],
    "admin.pages.edit": [
        {
            "name": "page",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.pages.update": [
        {
            "name": "page",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.banners.index": [],
    "admin.banners.store": [],
    "admin.testimonials.index": [],
    "admin.testimonials.create": [],
    "admin.testimonials.store": [],
    "admin.testimonials.edit": [
        {
            "name": "testimonial",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.testimonials.update": [
        {
            "name": "testimonial",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.index": [],
    "admin.users.create": [],
    "admin.users.store": [],
    "admin.users.edit": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.activate": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.deactivate": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.settings.index": [],
    "admin.settings.update": [],
    "webhook.whatsapp.verify": [],
    "webhook.whatsapp.handle": [],
    "webhook.shipping.jnt": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
