import {
  Archive,
  Article,
  ArrowsCounterClockwise,
  ArrowLeft,
  ArrowRight,
  ArrowDownLeft,
  ArrowUpRight,
  ArrowSquareOut,
  Bell,
  CalendarBlank,
  ChatCircleDots,
  CircleNotch,
  Globe,
  PaperPlaneTilt,
  PlugsConnected,
  ArrowsClockwise,
  ArrowsOutSimple,
  LinkSimple,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  ChartLineUp,
  ChatText,
  Check,
  Selection,
  CheckCircle,
  Checks,
  Circle,
  ClipboardText,
  Clock,
  ClockCounterClockwise,
  Columns,
  Copy,
  CreditCard,
  Cube,
  DoorOpen,
  DotsSixVertical,
  DotsThree,
  DotsThreeVertical,
  DownloadSimple,
  EnvelopeSimple,
  Eye,
  EyeSlash,
  File,
  FileText,
  Folder,
  FolderOpen,
  FolderPlus,
  Funnel,
  Gauge,
  GearSix,
  GridFour,
  Gavel,
  GitBranch,
  HandCoins,
  Money,
  Headset,
  House,
  ImageSquare,
  Info,
  List,
  Megaphone,
  Lightning,
  LockKey,
  Percent,
  MagnifyingGlass,
  MapPin,
  Minus,
  Moon,
  Package,
  PencilSimple,
  Phone,
  Play,
  Plus,
  Printer,
  QrCode,
  Question,
  Trash,
  TrashSimple,
  Tray,
  Warning,
  Receipt,
  Ruler,
  SealCheck,
  ShareNetwork,
  ShieldCheck,
  ShoppingCartSimple,
  Sidebar,
  SignOut,
  Stack,
  TagSimple,
  SlidersHorizontal,
  SortAscending,
  Sparkle,
  Star,
  Storefront,
  Sun,
  Ticket,
  TrendDown,
  TrendUp,
  Truck,
  UploadSimple,
  User,
  UserCircle,
  UserGear,
  UsersThree,
  VideoCamera,
  WhatsappLogo,
  Wrench,
  X,
  type IconProps,
} from "@phosphor-icons/react"
import type { ComponentType } from "react"

const iconRegistry: Record<string, ComponentType<IconProps>> = {
  archive: Archive,
  "alert-circle": Warning,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-down-left": ArrowDownLeft,
  "arrow-up-right": ArrowUpRight,
  "caret-down": CaretDown,
  "caret-left": CaretLeft,
  "caret-right": CaretRight,
  "caret-up": CaretUp,
  "chart-line": ChartLineUp,
  "badge-check": SealCheck,
  "check-circle": CheckCircle,
  check: Check,
  selection: Selection,
  checks: Checks,
  "chevron-down": CaretDown,
  "chevron-right": CaretRight,
  "chevron-up": CaretUp,
  "circle-check-big": CheckCircle,
  "circle-help": Question,
  "clipboard-list": ClipboardText,
  clock: Clock,
  "columns-3": Columns,
  copy: Copy,
  "credit-card": CreditCard,
  cube: Cube,
  "door-open": DoorOpen,
  download: DownloadSimple,
  "dots-three": DotsThree,
  "dots-six-vertical": DotsSixVertical,
  "dots-three-vertical": DotsThreeVertical,
  more: DotsThree,
  email: EnvelopeSimple,
  envelope: EnvelopeSimple,
  expand: ArrowsOutSimple,
  mail: EnvelopeSimple,
  eye: Eye,
  "eye-slash": EyeSlash,
  file: File,
  "file-text": FileText,
  folder: Folder,
  "folder-open": FolderOpen,
  "folder-plus": FolderPlus,
  funnel: Funnel,
  gauge: Gauge,
  gavel: Gavel,
  "grid-2x2": GridFour,
  "grid-3x3": GridFour,
  home: House,
  house: House,
  history: ClockCounterClockwise,
  "hand-coins": HandCoins,
  cod: Money,
  headset: Headset,
  "help-circle": Question,
  image: ImageSquare,
  images: ImageSquare,
  info: Info,
  lightning: Lightning,
  zap: Lightning,
  bolt: Lightning,
  "layout-grid": GridFour,
  "layout-dashboard": Gauge,
  lock: LockKey,
  "map-pin": MapPin,
  map: MapPin,
  megaphone: Megaphone,
  menu: List,
  moon: Moon,
  "message-circle": ChatText,
  minus: Minus,
  bell: Bell,
  package: Package,
  "package-open": Package,
  "panel-left": Sidebar,
  pencil: PencilSimple,
  "pencil-simple": PencilSimple,
  "pen-line": PencilSimple,
  pen: PencilSimple,
  phone: Phone,
  play: Play,
  plus: Plus,
  refresh: ArrowsClockwise,
  "receipt-text": Receipt,
  printer: Printer,
  ruler: Ruler,
  search: MagnifyingGlass,
  settings: GearSix,
  "shield-check": ShieldCheck,
  share: ShareNetwork,
  "shopping-cart": ShoppingCartSimple,
  "sign-out": SignOut,
  sliders: SlidersHorizontal,
  sort: SortAscending,
  star: Star,
  "git-branch": GitBranch,
  layers: Stack,
  "ticket-percent": Percent,
  tags: TagSimple,
  sun: Sun,
  storefront: Storefront,
  store: Storefront,
  sparkle: Sparkle,
  ticket: Ticket,
  voucher: Ticket,
  "trend-down": TrendDown,
  "trend-up": TrendUp,
  "trending-up": TrendUp,
  truck: Truck,
  upload: UploadSimple,
  user: User,
  "user-cog": UserGear,
  "user-round": User,
  "user-circle": UserCircle,
  users: UsersThree,
  video: VideoCamera,
  "video-camera": VideoCamera,
  warning: Warning,
  "alert-triangle": Warning,
  "clipboard-text": ClipboardText,
  "external-link": ArrowSquareOut,
  "message-square": ChatText,
  "messages-square": ChatText,
  list: List,
  inbox: Tray,
  link: LinkSimple,
  "magnifying-glass": MagnifyingGlass,
  qr: QrCode,
  "rotate-cw": ArrowsClockwise,
  sparkles: Sparkle,
  trash: Trash,
  "trash-2": TrashSimple,
  whatsapp: WhatsappLogo,
  wrench: Wrench,
  "shopping-basket": ShoppingCartSimple,
  box: Cube,
  x: X,
  // Alias fallback dinamis: nama umum selalu punya ikon, tidak pernah jatuh ke Circle
  description: Article,
  article: Article,
  notes: Article,
  chat: ChatCircleDots,
  "chat-circle": ChatCircleDots,
  "chat-bubble": ChatCircleDots,
  conversation: ChatCircleDots,
  gear: GearSix,
  cog: GearSix,
  spinner: CircleNotch,
  loading: CircleNotch,
  "circle-notch": CircleNotch,
  globe: Globe,
  web: Globe,
  website: Globe,
  "rotate-ccw": ArrowsCounterClockwise,
  "arrow-counter-clockwise": ArrowsCounterClockwise,
  // Ikon umum dinamis lain yang sering dipakai via variabel
  help: Question,
  question: Question,
  faq: Question,
  money: HandCoins,
  payment: CreditCard,
  payments: CreditCard,
  "credit-card-payment": CreditCard,
  chart: ChartLineUp,
  analytics: ChartLineUp,
  dashboard: Gauge,
  inventory: Package,
  stock: Package,
  shipping: Truck,
  delivery: Truck,
  courier: Truck,
  promo: Megaphone,
  campaign: Megaphone,
  banner: Megaphone,
  review: Star,
  reviews: Star,
  rating: Star,
  customer: User,
  customers: UsersThree,
  admin: UserGear,
  media: ImageSquare,
  photo: ImageSquare,
  document: FileText,
  docs: FileText,
  report: Receipt,
  reports: Receipt,
  "settings-system": GearSix,
  database: Stack,
  cache: Lightning,
  queue: List,
  log: FileText,
  logs: FileText,
  activity: ClockCounterClockwise,
  notification: Bell,
  notifications: Bell,
  close: X,
  cancel: X,
  success: CheckCircle,
  error: Warning,
  failed: Warning,
  pending: Clock,
  done: CheckCircle,
  complete: CheckCircle,
  completed: CheckCircle,
  view: Eye,
  preview: Eye,
  edit: PencilSimple,
  delete: Trash,
  remove: Trash,
  add: Plus,
  create: Plus,
  new: Plus,
  save: Check,
  send: PaperPlaneTilt,
  submit: PaperPlaneTilt,
  "download-cloud": DownloadSimple,
  export: DownloadSimple,
  import: UploadSimple,
  filter: Funnel,
  filters: Funnel,
  calendar: CalendarBlank,
  date: CalendarBlank,
  schedule: CalendarBlank,
  location: MapPin,
  address: MapPin,
  "store-settings": Storefront,
  shop: Storefront,
  cart: ShoppingCartSimple,
  order: Package,
  orders: Package,
  product: Cube,
  products: Cube,
  variant: SlidersHorizontal,
  variants: SlidersHorizontal,
  category: Stack,
  categories: Stack,
  "user-management": UsersThree,
  permission: ShieldCheck,
  security: LockKey,
  key: LockKey,
  api: PlugsConnected,
  integration: PlugsConnected,
  webhook: LinkSimple,
  circle: Circle,
}

export interface RagilIconProps extends IconProps {
  name: string
}

/**
 * Alias nama ikon yang tersimpan di database/setting tetapi tidak persis
 * dengan kunci registry (kontrak owner: ikon yang tidak terdaftar dicari
 * mandiri, bukan langsung jatuh ke Circle).
 */
const iconAliases: Record<string, string> = {
  cod: "money",
  shield: "security",
  "shield-check": "security",
  hand_coins: "hand-coins",
  handcoin: "hand-coins",
  layoutgrid: "grid-2x2",
  layout_grid: "grid-2x2",
  grid: "grid-2x2",
  image: "images",
  picture: "images",
  photo: "media",
  chat: "chat",
  chats: "chat",
  message: "chat",
  "message-circle": "chat",
  "message-square": "chat",
  trash2: "trash",
  cash: "money",
  coin: "hand-coins",
  coins: "hand-coins",
  guarantee: "security",
  warranty: "security",
  shipping_cost: "shipping",
}

/** Cari kunci registry untuk nama ikon apa pun dari database/setting. */
function resolveIconName(raw?: string | null): string | null {
  if (!raw) return null
  const trimmed = raw.trim()
  if (!trimmed) return null
  if (trimmed in iconRegistry) return trimmed

  // Bentuk umum: spasi/underscore menjadi dash, lalu huruf kecil.
  const dashed = trimmed.replace(/[\s_]+/g, "-").toLowerCase()
  if (dashed in iconRegistry) return dashed

  // Tanpa pemisah (mis. "handcoins", "layoutgrid").
  const compact = dashed.replace(/-/g, "")
  for (const key of Object.keys(iconRegistry)) {
    if (key.replace(/-/g, "") === compact) return key
  }

  // Alias manual terakhir.
  if (dashed in iconAliases && iconAliases[dashed] in iconRegistry) {
    return iconAliases[dashed]
  }

  return null
}

/** Benar bila nama ikon dikenali registry (dipakai test kontrak ikon). */
export function hasIcon(name: string): boolean {
  return resolveIconName(name) !== null
}

export function Icon({ name, weight = "regular", ...props }: RagilIconProps) {
  const resolved = resolveIconName(name)
  if (!resolved) return null
  const IconComponent = iconRegistry[resolved] ?? Circle
  return <IconComponent weight={weight} {...props} />
}
