import {
  Archive,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  ArrowSquareOut,
  Bell,
  ArrowsClockwise,
  ArrowsOutSimple,
  LinkSimple,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  ChartLineUp,
  ChatText,
  Check,
  CheckCircle,
  Checks,
  Circle,
  ClipboardText,
  Clock,
  ClockCounterClockwise,
  Columns,
  Copy,
  CreditCard,
  Cube,
  DoorOpen,
  DotsThree,
  DownloadSimple,
  EnvelopeSimple,
  Eye,
  File,
  FileText,
  Folder,
  FolderOpen,
  FolderPlus,
  Funnel,
  Gauge,
  GearSix,
  GridFour,
  Gavel,
  GitBranch,
  HandCoins,
  Headset,
  House,
  ImageSquare,
  Info,
  List,
  Megaphone,
  Lightning,
  LockKey,
  Percent,
  MagnifyingGlass,
  MapPin,
  Minus,
  Moon,
  Package,
  PencilSimple,
  Phone,
  Play,
  Plus,
  Printer,
  QrCode,
  Question,
  Trash,
  TrashSimple,
  Tray,
  Warning,
  Receipt,
  Ruler,
  SealCheck,
  ShareNetwork,
  ShieldCheck,
  ShoppingCartSimple,
  Sidebar,
  SignOut,
  Stack,
  TagSimple,
  SlidersHorizontal,
  SortAscending,
  Sparkle,
  Star,
  Storefront,
  Sun,
  Ticket,
  TrendDown,
  TrendUp,
  Truck,
  UploadSimple,
  User,
  UserCircle,
  UserGear,
  UsersThree,
  VideoCamera,
  WhatsappLogo,
  Wrench,
  X,
  type IconProps,
} from "@phosphor-icons/react"
import type { ComponentType } from "react"

const iconRegistry: Record<string, ComponentType<IconProps>> = {
  archive: Archive,
  "alert-circle": Warning,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  "caret-down": CaretDown,
  "caret-left": CaretLeft,
  "caret-right": CaretRight,
  "caret-up": CaretUp,
  "chart-line": ChartLineUp,
  "badge-check": SealCheck,
  "check-circle": CheckCircle,
  check: Check,
  checks: Checks,
  "chevron-down": CaretDown,
  "chevron-right": CaretRight,
  "chevron-up": CaretUp,
  "circle-check-big": CheckCircle,
  "circle-help": Question,
  "clipboard-list": ClipboardText,
  clock: Clock,
  "columns-3": Columns,
  copy: Copy,
  "credit-card": CreditCard,
  cube: Cube,
  "door-open": DoorOpen,
  download: DownloadSimple,
  "dots-three": DotsThree,
  more: DotsThree,
  email: EnvelopeSimple,
  envelope: EnvelopeSimple,
  expand: ArrowsOutSimple,
  mail: EnvelopeSimple,
  eye: Eye,
  file: File,
  "file-text": FileText,
  folder: Folder,
  "folder-open": FolderOpen,
  "folder-plus": FolderPlus,
  funnel: Funnel,
  gauge: Gauge,
  gavel: Gavel,
  "grid-2x2": GridFour,
  "grid-3x3": GridFour,
  home: House,
  house: House,
  history: ClockCounterClockwise,
  "hand-coins": HandCoins,
  headset: Headset,
  "help-circle": Question,
  image: ImageSquare,
  images: ImageSquare,
  info: Info,
  lightning: Lightning,
  zap: Lightning,
  bolt: Lightning,
  "layout-grid": GridFour,
  "layout-dashboard": Gauge,
  lock: LockKey,
  "map-pin": MapPin,
  map: MapPin,
  megaphone: Megaphone,
  menu: List,
  moon: Moon,
  "message-circle": ChatText,
  minus: Minus,
  bell: Bell,
  package: Package,
  "panel-left": Sidebar,
  pencil: PencilSimple,
  "pencil-simple": PencilSimple,
  "pen-line": PencilSimple,
  pen: PencilSimple,
  phone: Phone,
  play: Play,
  plus: Plus,
  refresh: ArrowsClockwise,
  "receipt-text": Receipt,
  printer: Printer,
  ruler: Ruler,
  search: MagnifyingGlass,
  settings: GearSix,
  "shield-check": ShieldCheck,
  share: ShareNetwork,
  "shopping-cart": ShoppingCartSimple,
  "sign-out": SignOut,
  sliders: SlidersHorizontal,
  sort: SortAscending,
  star: Star,
  "git-branch": GitBranch,
  layers: Stack,
  "ticket-percent": Percent,
  tags: TagSimple,
  sun: Sun,
  storefront: Storefront,
  store: Storefront,
  sparkle: Sparkle,
  ticket: Ticket,
  voucher: Ticket,
  "trend-down": TrendDown,
  "trend-up": TrendUp,
  "trending-up": TrendUp,
  truck: Truck,
  upload: UploadSimple,
  user: User,
  "user-cog": UserGear,
  "user-round": User,
  "user-circle": UserCircle,
  users: UsersThree,
  video: VideoCamera,
  "video-camera": VideoCamera,
  warning: Warning,
  "alert-triangle": Warning,
  "clipboard-text": ClipboardText,
  "external-link": ArrowSquareOut,
  "message-square": ChatText,
  list: List,
  inbox: Tray,
  link: LinkSimple,
  "magnifying-glass": MagnifyingGlass,
  qr: QrCode,
  "rotate-cw": ArrowsClockwise,
  sparkles: Sparkle,
  trash: Trash,
  "trash-2": TrashSimple,
  whatsapp: WhatsappLogo,
  wrench: Wrench,
  "shopping-basket": ShoppingCartSimple,
  box: Cube,
  x: X,
}

export interface RagilIconProps extends IconProps {
  name: string
}

export function Icon({ name, weight = "regular", ...props }: RagilIconProps) {
  const IconComponent = iconRegistry[name] ?? Circle
  return <IconComponent weight={weight} {...props} />
}

export function hasIcon(name: string): boolean {
  return name in iconRegistry
}
