import {
  Archive,
  ArrowLeft,
  ArrowRight,
  ArrowsClockwise,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  ChartLineUp,
  ChatCircle,
  Check,
  CheckCircle,
  Circle,
  ClipboardText,
  Clock,
  ClockCounterClockwise,
  Columns,
  CreditCard,
  Cube,
  DoorOpen,
  DotsThree,
  DownloadSimple,
  EnvelopeSimple,
  Eye,
  File,
  FileText,
  Funnel,
  Gauge,
  GearSix,
  GridFour,
  Gavel,
  HandCoins,
  Headset,
  House,
  ImageSquare,
  Info,
  List,
  Lightning,
  LockKey,
  MagnifyingGlass,
  MapPin,
  Minus,
  Moon,
  Package,
  PencilSimple,
  Phone,
  Plus,
  Question,
  Receipt,
  Ruler,
  SealCheck,
  ShieldCheck,
  ShoppingCartSimple,
  Sidebar,
  SignOut,
  SlidersHorizontal,
  SortAscending,
  Sparkle,
  Star,
  Storefront,
  Sun,
  Ticket,
  TrendUp,
  Truck,
  UploadSimple,
  UserCircle,
  UserGear,
  UsersThree,
  WarningCircle,
  WhatsappLogo,
  X,
  type IconProps,
} from "@phosphor-icons/react"
import type { ComponentType } from "react"

const iconRegistry: Record<string, ComponentType<IconProps>> = {
  archive: Archive,
  "alert-circle": WarningCircle,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "caret-down": CaretDown,
  "caret-left": CaretLeft,
  "caret-right": CaretRight,
  "caret-up": CaretUp,
  "chart-line": ChartLineUp,
  "badge-check": SealCheck,
  "check-circle": CheckCircle,
  check: Check,
  "chevron-down": CaretDown,
  "chevron-right": CaretRight,
  "chevron-up": CaretUp,
  "circle-check-big": CheckCircle,
  "circle-help": Question,
  "clipboard-list": ClipboardText,
  clock: Clock,
  "columns-3": Columns,
  "credit-card": CreditCard,
  cube: Cube,
  "door-open": DoorOpen,
  download: DownloadSimple,
  "dots-three": DotsThree,
  more: DotsThree,
  envelope: EnvelopeSimple,
  email: EnvelopeSimple,
  mail: EnvelopeSimple,
  eye: Eye,
  file: File,
  "file-text": FileText,
  funnel: Funnel,
  gauge: Gauge,
  gavel: Gavel,
  "grid-2x2": GridFour,
  "grid-3x3": GridFour,
  home: House,
  house: House,
  history: ClockCounterClockwise,
  "hand-coins": HandCoins,
  headset: Headset,
  "help-circle": Question,
  image: ImageSquare,
  images: ImageSquare,
  info: Info,
  lightning: Lightning,
  "layout-grid": GridFour,
  "layout-dashboard": Gauge,
  lock: LockKey,
  "map-pin": MapPin,
  map: MapPin,
  menu: List,
  moon: Moon,
  "message-circle": ChatCircle,
  minus: Minus,
  package: Package,
  "panel-left": Sidebar,
  pencil: PencilSimple,
  phone: Phone,
  plus: Plus,
  refresh: ArrowsClockwise,
  "receipt-text": Receipt,
  ruler: Ruler,
  search: MagnifyingGlass,
  settings: GearSix,
  "shield-check": ShieldCheck,
  "shopping-cart": ShoppingCartSimple,
  "sign-out": SignOut,
  sliders: SlidersHorizontal,
  sort: SortAscending,
  star: Star,
  sun: Sun,
  storefront: Storefront,
  store: Storefront,
  sparkle: Sparkle,
  ticket: Ticket,
  voucher: Ticket,
  "trend-up": TrendUp,
  "trending-up": TrendUp,
  truck: Truck,
  upload: UploadSimple,
  user: UserCircle,
  "user-cog": UserGear,
  "user-round": UserCircle,
  users: UsersThree,
  warning: WarningCircle,
  whatsapp: WhatsappLogo,
  "shopping-basket": ShoppingCartSimple,
  box: Cube,
  x: X,
}

export interface RagilIconProps extends IconProps {
  name: string
}

export function Icon({ name, weight = "regular", ...props }: RagilIconProps) {
  const IconComponent = iconRegistry[name] ?? Circle
  return <IconComponent weight={weight} {...props} />
}

export function hasIcon(name: string): boolean {
  return name in iconRegistry
}
